mutation CreateKpi($input: CreateKpiInput!) {
    createKpi(input: $input) {
        entity {
            name
            description
            frequency
        }

        errors {
            field
            errors
        }
        success
    }
}