mutation($id:String, $input: KPIAttributesInput) {
  updateKPI(id: $id, input: $input) {
    entity {
      _id
      code
      name
      baseKpi
      description
      source
      group
      groupings
      dateRange {
        predefined
        custom {
          from
          to
        }
      }
      filter
      frequency
      axisSelection
      emptyValueReplacement
      expression
      type
      createdBy
      createdDate
      updatedBy
      updatedDate
    }
    errors {
      field
      errors
    }
    success
  }
}
