query Locations {
    locations {
        _id
        name
        description
        tags
        businessunits
        operhours {
            day
            from
            to
            fromAMPM
            toAMPM
        }
        street
        city
        state
        country
        zip
        timezone
    }
}