query FindTarget($id: String) {
    findTarget(id: $id) {
        _id
        datepicker
        vary
        amount
        amountBy
        period
        owner
        target
        visible
        notify
        chart
        stackName
    }
}