mutation RemoveTarget($id: String, $owner: String) {
    removeTarget(id: $id, owner: $owner) {
        success
        errors {
            errors
            field
        }
        entity {
            _id
        }
    }
}