mutation RemoveTargetFromChart($id: String) {
    removeTargetFromChart(id: $id) {
        success
        errors {
            errors
            field
        }
        entity {
            _id
        }
    }
}