query DataEntries {
  dataEntries {
    _id
    name
    description
    dataSource
    externalSource
    fields {
      name
      path
      type
      sourceOrigin
    }
    filterOperators {
      Number {
        description
        name
        
      }
      String {
        description
        name
      }
    }
    sources
    dataEntry
    users
  }
}