query AllUsers {
    allUsers {
        _id
        username
        roles {
            name
            permissions {
                action
                subject
            }
        }
        profile {
            firstName
            lastName
            timezone
        }
        emails {
            address
        }
        profilePictureUrl
    }
}