mutation createMilestone($input: MilestoneInput!) {
  createMilestone(input: $input) {
    entity {
      _id
      target
      task
      dueDate
      status
    },
    success,
    errors {
      field
    }
  }
}