query ListChartQuery {
    listCharts {
      data {
        _id
        title
        subtitle
        frequency
        chartDefinition
        group
        kpis { type, kpi }
        groupings
        xAxisSource
        dateRange {
          predefined
            custom {
              from
              to
            }
          }
        }
    }
}
