mutation UpdateUserPreference($id: String!, $input: ITourInput) {
    updateUserPreference(id: $id, input: $input) {
        success
        errors {
            errors
            field
        }
        entity {
            preferences {
                dashboardIdNoVisible
            }
        }
    }
}