mutation UpdateDashboard($id: String!, $input: DashboardInput!){
   updateDashboard (id: $id, input: $input) {
    entity {
      name
      description
      charts
      widgets
      visible
      order
    }
     errors {
      field
      errors
    }
    success
	}
}
