query AllUsers {
    allUsers {
        _id
        username
        roles
        profile {
            firstName
            lastName
            lastName
        }
        emails {
            address
        }
        timestamps
    }
}