mutation UpdateKpi($id: String!, $input: UpdateKpiInput!) {
    updateKpi(id: $id, input: $input){

        entity {
            name
            description
            frequency
        }

        errors{
            field
            errors
        }
        success
    }
} 