query MapMarkersForDashboard($input: MapMarkerGroupingInput) {
  mapMarkers(type: "customerAndZip", input: $input) {
    name
    lat
    lng
    value
    color
    groupingName
    itemList {
      amount
      groupName
    }
  }
}