mutation updateUserPreference($id: String!, $input: UserPreferencesInput) {
  updateUserPreference(id: $id, input: $input) {
    success
    entity {
      preferences {
        helpCenter
        theme
      }
    }
  }
}