mutation UpdateUserPreference($id: String!, $input: ITourInput) {
    updateUserPreference(id: $id, input: $input) {
        success
        errors {
            errors
            field
        }
        entity {
            preferences {
                dashboards {
                    listMode
                }
                 charts {
                listMode
                }
                kpis {
                    listMode
                }
                roles {
                    listMode
                }
                users {
                    listMode
                }
            }
        }
    }
}