mutation CreateBusinessUnit($input: CreateBusinessUnitInput!) {
    createBusinessUnit(input: $input) {
        entity {
            name
            serviceType
        }

        errors {
            field
            errors
        }
        success
    }
}