mutation UpdateUserAgreement($input: UserAgreementInput) {
    updateUserAgreement(input: $input) {
        entity {
            username
        }
        errors {
            field
            errors
        }
    }
}