query AllUsers {
    allUsers {
        _id
        username
        roles {
            name
        }
        profile {
            firstName
            lastName
            timezone
        }
        profilePictureUrl
        emails {
            address
        }
        timestamps
    }
}