mutation CreateScheduleJob($input: ScheduleJobInput) {
    createScheduleJob(input: $input) {
        entity {
            notifyUsers
            frequency
            active
            pushNotification
            emailNotified
            modelAlert {
                name
                id
            }
        }
        success
        errors {
            field
            errors
        }
    }
}