mutation RemoveScheduleJob($id: String!) {
    removeScheduleJob(id: $id) {
        success
        errors {
            field
            errors
        }

        entity {
            notifyUsers
            frequency
            active
            pushNotification
            emailNotified
            modelAlert {
                name
                id
            }
        }
    }
}