query ScheduleJobByWidgetId($id: String!) {
    scheduleJobByWidgetId(id: $id) {
        _id
        notifyUsers
        frequency
        active
        pushNotification
        emailNotified
        modelAlert {
            name
            id
        }
    }
}