query PreviewWidget($input: WidgetInput) {
  previewWidget(input: $input) {
    materialized {
        value
        comparison {
          period
          value
          arrowDirection
        }
        chart
    }
  } 
}