mutation UpdateTarget($id: String, $data: TargetNewInput) {
    updateTargetNew(id: $id, data: $data) {
        success
        entity {
            datepicker
            vary
            amount
            amountBy
            type
            period
            notify {
                users
                notification
            }
            visible
            owner
            chart
        }
        errors {
            field
            errors
        }
    }
}