query WidgetListNoData($materialize: Boolean) {
  listWidgets(materialize: $materialize) {
    _id
    order
    name
    description
    type
    size
    color
    fontColor
    hasAlerts
    chartWidgetAttributes {
      chart
    }
    numericWidgetAttributes {
      kpi
      comparison
      comparisonArrowDirection
      trending
      format
    }
  } 
}