query WidgetList {
  listWidgets {
    _id
    order
    name
    description
    type
    size
    color
    fontColor
    chartWidgetAttributes {
      chart
    }
    numericWidgetAttributes {
      kpi
      comparison
      comparisonArrowDirection
      trending
      format
    }

    materialized {
        value
        comparison {
          period
          value
          arrowDirection
        }
        trending
        chart
    }
  } 
}