query targetsBySource($source: SourceNewInput!) {
  targetBySource(source: $source) {
    _id
    name
    source {
      type
      identifier
    }
    compareTo
    type
    appliesTo
    value
    unit
    notificationConfig{
      users {
        identifier
        deliveryMethods
      }
    }
    milestones {
      task
      dueDate
      status
      responsible
    }
    active
  }
}