mutation ResetPassword($token: String!, $password: String!, $enrollment: Boolean, $profile: InputUserProfile, $companyName: String) {
    resetPassword(token: $token, password: $password, enrollment: $enrollment, profile: $profile, companyName: $companyName) {
        success
    }
}