mutation CreateLocation($input: LocationInput){
  createLocation(input: $input) {
    entity {
        _id
        name
        description
        tags
        businessunits
        operhours {
            day
            from
            to
            fromAMPM
            toAMPM
        }
        street
        city
        state
        country
        zip
        timezone
    }
    errors {
      field
    }
    success
  }
}