query DataSources {
	dataSources {
	    name
        description
        dataSource
        externalSource
        fields {
            name
            path
            type
            allowGrouping
        }
        sources
        
	} 
}
