mutation UpdateBusinessUnit($input: UpdateBusinessUnitInput!) {
    updateBusinessUnit(input: $input){

        entity {
            name
            serviceType
        }

        errors{
            field
            errors
        }
        success
    }
} 