query Appointments($start: String!, $end: String!) {
   appointments(start: $start, end: $end) {
     _id
     source
     reason
     comments
     from
     to
     duration
     cancelled
     customer {
       externalId
       fullname
     }
     location {
       externalId
       name
     }
     provider {
       externalId
       name
     }
     reason
     event {
       color
     }
  }
  
}