mutation UpdateUserPreference($id: String!, $input: UserPreferencesInput) {
    updateUserPreference(id: $id, input: $input) {
        success
        errors {
            errors
            field
        }
        entity {
            preferences {
                chart {
                    showTour
                }
                showAppointmentCancelled
                mobileCalendar
                calendarTimeZone
            }
        }
    }
}