query AllUsers {
    allUsers {
        _id
        username
        roles {
            name
        }
        profile {
            firstName
            lastName
            lastName
        }
        emails {
            address
        }
        timestamps
        profilePictureUrl
    }
}