query DataSources {
	dataSources {
	    name
        description
        dataSource
        fields {
            name
            path
            type
            allowGrouping
            available
        }
	} 
}
